[project]
name = "mohan-desktop-assistant-preview"
version = "4.6.0"
description = "The limited cross-platform Preview of MoHan Desktop Assistant."
requires-python = ">=3.15,<3.16"
license = "MIT"
authors = [
  { name = "Flameblade Studio" },
]
dependencies = [
  "PySide6_Essentials==6.12.0",
  "PySide6_Addons==6.12.0",
  "shiboken6==6.12.0",
]

[project.urls]
Homepage = "https://www.flamebladestudio.com.tw/mohan-desktop-assistant/"
Repository = "https://github.com/flameblade-studio/MoHan-PC-Desktop-Assistant"
Issues = "https://github.com/flameblade-studio/MoHan-PC-Desktop-Assistant/issues"
