changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: "✨ 新功能 / 新功能 / New features / 新機能"
      labels:
        - enhancement
        - feature
    - title: "🐛 修正 / 修复 / Fixes / 修正"
      labels:
        - bug
        - fix
    - title: "🔐 安全性 / 安全性 / Security / セキュリティ"
      labels:
        - security
    - title: "📚 文件 / 文档 / Documentation / ドキュメント"
      labels:
        - documentation
    - title: "📦 相依套件 / 依赖项 / Dependencies / 依存関係"
      labels:
        - dependencies
    - title: "🛠 其他變更 / 其他变更 / Other changes / その他の変更"
      labels:
        - "*"
