from __future__ import annotations

lazy from collections.abc import Mapping

from presentation.ui_localization_en import ENGLISH_UI_TEXT as _ENGLISH
from presentation.ui_localization_ja import JAPANESE_UI
lazy from domain.immutable_config import deep_freeze
lazy from domain.language_support import is_english, is_japanese, is_simplified_chinese

_SIMPLIFIED_CHINESE: Mapping[str, str] = deep_freeze(
{'first_run_title': '首次启动设置',
 'first_run_brand': '墨寒  MoHan',
 'first_run_heading': '<b>欢迎使用墨寒桌面助手</b>',
 'first_run_hero_tagline': '来自北宋的千年女剑魂，陪您说话、记忆，也陪您把工作做好。',
 'first_run_intro': '请先建立用户设置。以下内容以后都能在“设置”页修改，不会绑定特定公司、职业或工作平台。',
 'assistant_name': '助手名称',
 'user_title': '助手对您的称呼',
 'organization_name': '公司／团队名称',
 'window_title': '完整窗口标题',
 'work_type': '工作类型',
 'ui_language': '界面与回复语言',
 'wake_word': '语音唤醒词',
 'assistant_name_placeholder': '例如：墨寒、Ava、Office Mate',
 'user_title_placeholder': '例如：主上、Alex、主管',
 'organization_placeholder': '公司、工作室或团队名称；个人使用可留空',
 'window_title_placeholder': '留空时自动使用“助手名称 · 组织名称”',
 'wake_word_placeholder': '例如：墨寒',
 'first_run_note': '工作平台页初始为空。请只添加您实际使用的公司系统、协作工具、管理后台或网站。',
 'finish_setup': '完成设置并开始使用',
 'required_title': '缺少必要信息',
 'required_identity': '请填写助手名称，以及助手对您的称呼。',
 'mode': '模式',
 'start_work': '开始工作',
 'stop_work': '结束工作',
 'tab_chat': '对话',
 'tab_today': '今日待办',
 'tab_platforms': '工作平台',
 'tab_memory': '长期记忆',
 'tab_voice': '语音',
 'tab_permissions': '电脑权限',
 'tab_settings': '设置',
 'tab_wardrobe': '云裳阁',
 'cancel_without_saving': '取消（不保存）',
 'restore_dashboard_window': '还原窗口',
 'restore_dashboard_window_tooltip': '将控制中心还原为可移动、可调整大小的窗口',
 'wardrobe_import': '导入服装套件',
 'wardrobe_apply': '应用所选服装',
 'wardrobe_restore_builtin': '恢复内置服装',
 'wardrobe_package_list': '套件列表',
 'wardrobe_compatibility_status': '兼容状态',
 'wardrobe_status': '状态',
 'wardrobe_no_packages': '尚未安装服装套件',
 'wardrobe_default_outfit': '内置默认服装',
 'wardrobe_compatible': '兼容',
 'wardrobe_incompatible': '不兼容',
 'wardrobe_status_ready': '云裳系统已就绪',
 'wardrobe_validator_pending': '套件未通过完整全视角与安全验证，因此未安装。',
 'wardrobe_assets_pending': '这套服装未具备完整全视角素材，无法应用。',
 'wardrobe_builtin_applied': '已应用内置默认服装。',
 'wardrobe_outfit_applied': '已应用所选完整服装。',
 'wardrobe_autonomous_enabled': '允许墨寒自主选装',
 'wardrobe_self_generation_enabled': '允许墨寒云端自创新衣（可能产生费用）',
 'wardrobe_trend_search_enabled': '允许以五类情境搜索流行趋势作为原创灵感（可能产生费用）',
 'wardrobe_generation_trend_search': '正在使用已同意的五类情境搜索趋势，随后生成、审核并打包新衣（可能产生费用）……',
 'wardrobe_image_quality': '云端制衣画质',
 'wardrobe_quality_low': '快速（画质较低，最省时省费）',
 'wardrobe_quality_medium': '标准（建议）',
 'wardrobe_quality_high': '精致（最耗时，费用最高）',
 'wardrobe_generated_limit': '自创服装保留上限',
 'wardrobe_storage_limit': '自创服装容量上限',
 'wardrobe_manual_lock_hours': '手动换装锁定时数',
 'wardrobe_manual_lock_off': '不锁定',
 'wardrobe_generate_now': '立即生成新衣（将使用图片 API）',
 'wardrobe_generation_starting': '正在创建 31 视角新衣并执行安全审核……',
 'wardrobe_generation_running': '正在生成、审核并打包新衣……',
 'wardrobe_generation_installed': '新衣已通过审核、安装并应用。',
 'wardrobe_generation_installed_manual_lock': '新衣已通过审核并安装；当前手动衣装仍在锁定期，因此保持不变。',
 'wardrobe_generation_activation_failed': '新衣已通过审核并安装，但无法安全应用；当前衣装保持不变。',
 'wardrobe_generation_not_enabled': '请先勾选允许云端自创新衣。',
 'wardrobe_generation_no_key': '尚未设置可用的 OpenAI API Key。',
 'wardrobe_generation_capacity': '已达到自创服装容量或冷却限制。',
 'wardrobe_generation_cooldown': '自动生成仍在失败冷却期；可按“立即生成新衣”手动重试。',
 'wardrobe_generation_quarantined': '新衣未通过审核，已隔离且未应用。',
 'wardrobe_generation_failed': '新衣生成失败，未安装任何素材。',
 'wardrobe_generation_rate_limited': '图片服务当前流量繁忙；墨寒已安全重试，稍后可从既有进度继续。',
 'wardrobe_generation_auth_failed': 'OpenAI API Key 验证失败，请在设置页重新保存密钥。',
 'wardrobe_generation_access_denied': '当前的 OpenAI 项目尚无 GPT Image 2 使用权限，或尚未完成组织验证。',
 'wardrobe_generation_moderation_blocked': '这次图像请求未通过供应方内容检查，未存入服装库。',
 'wardrobe_generation_invalid_request': '图片服务拒绝了生成规格；错误已保留以供修复，未安装不完整素材。',
 'wardrobe_generation_network_unavailable': '当前无法连接图片服务，未安装不完整素材。',
 'wardrobe_generation_provider_unavailable': '图片服务暂时不可用，未安装不完整素材。',
 'wardrobe_automatic_selection_disabled': '自主选装目前已关闭。',
 'wardrobe_automatic_selection_failed': '自主选装评估失败，已保留当前衣装。',
 'wardrobe_automatic_outfit_selected': '墨寒已根据情境自主换装。',
 'wardrobe_pavilion_subtitle': '让墨寒依天气、心情与场合挑选完整造型，也保留您的决定。',
 'wardrobe_source_policy': '来源分流：炎剑官方・用户导入・墨寒自创',
 'dashboard_brand_line': '墨色为骨・寒光为心',
 'wardrobe_character_preview': '墨寒造型预览',
 'wardrobe_view_front': '正面',
 'wardrobe_view_left': '左侧',
 'wardrobe_view_right': '右侧',
 'wardrobe_view_back': '背面',
 'wardrobe_upload_single_file': '上传单个文件',
 'wardrobe_installed_inactive': '已安装，未启用',
 'wardrobe_outfit_preview': '服装预览',
 'wardrobe_hairstyle_preview': '发型预览',
 'wardrobe_headwear_accessories': '头饰与配件',
 'wardrobe_preview_complete_look': '一键预览整套造型',
 'wardrobe_changes_after_save': '保存后生效',
 'wardrobe_cancel_restores': '取消并恢复',
 'wardrobe_remove_package': '移除扩展包',
 'wardrobe_delete_confirm': '确定移除「{package}」吗？',
 'wardrobe_builtin_not_removable': '内置包无法移除',
 'wardrobe_switch_before_remove': '请先切换，再移除正在使用的包',
 'wardrobe_missing_package_fallback': '缺少套件，已保留当前造型',
 'theme_preview': '主题预览',
 'theme_section_title': '<b>控制台主题</b>',
 'theme_restore': '还原主题',
 'theme_source_official': '炎剑官方',
 'theme_source_user': '用户自制',
 'package_rejected_unsafe_or_missing': '套件含危险内容或缺少文件，已整包拒绝',
 'appearance_category_outfit': '衣装',
 'appearance_category_hairstyle': '发型',
 'appearance_category_headwear': '头饰',
 'appearance_category_accessory': '配件',
 'appearance_no_headwear': '无头饰',
 'today_input_placeholder': '输入待办标题，例如：完成漫画第 3 话分镜',
 'todo_category_comic': '漫画',
 'todo_category_article': '文章',
 'todo_category_music': '音乐',
 'todo_category_stickers': '贴图',
 'todo_category_publishing': '出版',
 'todo_category_administration': '行政',
 'todo_category_other': '其他',
 'add_todo': '＋ 添加待办',
 'save_as_idea': '✦ 保存灵感',
 'today_tasks_heading': '<b>今天要做</b>',
 'creative_ideas_heading': '<b>创作灵感</b>',
 'edit_selected_idea': '编辑选中灵感',
 'edit_selected_idea_tooltip': '也可以双击下方任一灵感',
 'delete_checked_ideas': '删除勾选灵感',
 'delete_checked_ideas_tooltip': '只删除已勾选的灵感，执行前会再次确认',
 'todo_complete_tooltip': '标记为已完成',
 'todo_category_suffix': '今日待办',
 'delete': '删除',
 'delete_todo_tooltip': '删除这项待办',
 'idea_editor_title': '编辑创作灵感',
 'idea_title': '<b>灵感标题</b>',
 'idea_title_placeholder': '为这则灵感填写清楚的标题',
 'idea_content': '<b>灵感内容</b>',
 'idea_content_placeholder': '记录情节、画面、对白、音乐方向或后续可执行的想法……',
 'cancel': '取消',
 'save_idea': '保存灵感',
 'idea_title_required_title': '缺少标题',
 'idea_title_required': '请先填写灵感标题。',
 'todo_count': '{count} 项未完成',
 'todo_empty': '今日待办尚空。\n请先写下一件真正重要的事。',
 'idea_count': '{count} 则',
 'idea_empty': '尚无灵感记录；输入上方文字后点击“保存灵感”。',
 'idea_edit_tooltip': '双击打开并编辑标题与内容',
 'today_time': '今日 {total}｜{state}',
 'timing_active': '计时中',
 'timing_inactive': '未计时',
 'todo_title_required': '请先输入待办标题。',
 'todo_added': '✓ 已添加待办：{text}',
 'todo_added_speech': '已收入今日待办。',
 'idea_capture_required': '请先输入要保存的灵感。',
 'idea_added': '✓ 已保存灵感：{text}',
 'idea_added_speech': '灵感稍纵即逝，妾已替您收好。',
 'idea_select_edit': '请先选择一则要编辑的灵感。',
 'idea_not_found': '找不到这则灵感，请刷新后再试。',
 'idea_updated': '✓ 已更新灵感：{title}',
 'idea_select_delete': '请先勾选要删除的灵感。',
 'idea_delete_title': '删除创作灵感',
 'idea_delete_confirm': '确定永久删除勾选的 {count} 则灵感吗？',
 'idea_deleted': '✓ 已删除 {count} 则灵感。',
 'platform_name_placeholder': '平台、系统或工具名称，例如：公司 ERP、Notion、客户后台',
 'platform_url_placeholder': '网址（可留空，例如：https://example.com）',
 'add_platform': '添加工作平台',
 'platform_filter_all': '全部平台',
 'platform_filter_active': '进行中',
 'platform_filter_blocked': '待补资料／受阻',
 'platform_filter_finished': '已完成／已发布',
 'platform_filter_not_started': '尚未开始',
 'save_all_platforms': '立即保存全部',
 'show': '显示',
 'platform_empty': '尚未建立工作平台。\n请在上方输入公司系统、协作工具、客户后台或任何工作平台。',
 'platform_intro': '集中管理工作中使用的平台、系统、客户入口或协作工具。每位用户都可以建立自己的工作平台，不预设绑定任何行业。',
 'platform_auto_save_note': '修改后会自动保存；也可以使用每张卡片的保存按钮。',
 'platform_item_placeholder': '当前负责的工作事项、项目或案件',
 'platform_missing_placeholder': '待补资料、等待他人回复或其他阻碍；没有可留空',
 'platform_next_placeholder': '下一个具体动作与期限',
 'platform_notes_placeholder': '备注、规则、联系窗口或其他补充',
 'platform_url_card_placeholder': 'https://…（可留空）',
 'platform_not_saved': '尚未保存',
 'save_platform': '保存此平台',
 'platform_field_item': '工作事项／项目',
 'platform_field_missing': '待补资料／阻碍',
 'platform_field_next': '下一步',
 'platform_field_notes': '备注',
 'platform_field_url': '网址',
 'open_platform': '打开网站／工具',
 'delete_platform': '删除平台',
 'platform_updated': '更新：{updated}',
 'platform_updated_unknown': '更新时间未知',
 'save_changes': '保存修改',
 'platform_waiting_auto_save': '{platform} 有修改，正在等待自动保存……',
 'platform_validation_finished_blocked': '注意：工作已完成，但仍列有待补资料或阻碍。',
 'platform_validation_revision_details': '请在待补资料／阻碍、下一步或备注中写明需修改的内容。',
 'platform_validation_not_started_data': '已有工作资料，请确认状态是否应改为“准备资料”。',
 'platform_validation_item_name': '建议填写工作事项、项目或案件名称，日后较容易辨认。',
 'platform_summary_unsaved': '｜未保存 {count}',
 'platform_summary': '{total} 个平台｜已完成 {finished}｜进行中 {active}｜尚未开始 {not_started}｜待补／阻碍 '
                     '{blocked}{unsaved}',
 'platform_saved': '{platform} 已保存。',
 'platform_saved_automatic': '{platform} 已自动保存。',
 'all_platforms_saved': '全部工作平台已保存；{count} 个平台仍列有待补资料或阻碍。',
 'all_platforms_saved_speech': '工作平台已保存。仍有 {count} 个平台标有待补资料或阻碍。',
 'memory_intro': '墨寒只保存您允许留下的人物、偏好、目标、工作流程与重要日期。记忆保存在本机，可按分类浏览、逐项编辑或删除。',
 'memory_input_placeholder': '例如：先完成漫画，再处理行政工作',
 'remember': '让墨寒记住',
 'memory_filter_label': '分类浏览',
 'all_memories': '全部记忆',
 'edit_selected_memory': '编辑选中记忆',
 'edit_memory_tooltip': '也可以双击下方任一记忆',
 'delete_checked_memories': '删除勾选记忆',
 'delete_checked_memories_tooltip': '只删除已勾选的记忆，执行前会再次确认',
 'clear_all_memories': '清除全部记忆',
 'optimize_memories': '安全整理记忆',
 'optimize_memories_tooltip': '合并低重要度重复内容，超量旧记忆只会先封存',
 'view_archived_memories': '查看已封存记忆',
 'auto_memory': '从“请记住／我喜欢／我习惯”等明确说法自动建立记忆',
 'memory_count': '{count} 则',
 'memory_empty': '这个分类目前没有记忆。',
 'memory_source_manual_short': '手动',
 'memory_source_conversation_short': '对话',
 'memory_untitled': '未命名记忆',
 'memory_item': '【{category}】{title}\u3000重要度 {importance}／5\n'
                '{content}\n'
                '来源：{source}\u3000更新：{updated}',
 'memory_added_speech': '妾已记下。您日后若要更改，也可逐项整理。',
 'memory_select_edit_title': '尚未选中',
 'memory_select_edit': '请先选择一则要编辑的记忆。',
 'memory_not_found_title': '找不到记忆',
 'memory_not_found': '这则记忆已不存在，列表将重新整理。',
 'memory_save_failed_title': '无法保存记忆',
 'memory_save_failed': '可能已有内容完全相同的记忆。原有数据未被更改。',
 'memory_select_delete_title': '尚未勾选',
 'memory_select_delete': '请先勾选要删除的记忆。',
 'memory_delete_title': '删除长期记忆',
 'memory_delete_confirm': '确定永久删除勾选的 {count} 则记忆吗？',
 'memory_clear_title': '清除长期记忆',
 'memory_clear_confirm': '确定删除墨寒保存的全部长期记忆吗？此操作无法恢复。',
 'memory_optimize_title': '记忆整理完成',
 'memory_optimize_result': '合并 {deduplicated} 则近似记忆，封存 {pruned} 则较旧低重要度记忆。\n'
                           '目前使用中 {active} 则；可恢复封存 {archived} 则。',
 'memory_editor_title': '编辑长期记忆',
 'memory_title_label': '<b>记忆标题</b>',
 'memory_title_placeholder': '用一句短标题识别这则记忆',
 'memory_category_label': '<b>分类</b>',
 'memory_importance_label': '<b>重要度</b>',
 'memory_content_label': '<b>记忆内容</b>',
 'memory_content_placeholder': '完整记录人物背景、偏好、目标、工作流程或重要日期……',
 'memory_source_manual': '手动建立',
 'memory_source_conversation': '由对话明确记住',
 'memory_metadata': '来源：{source}\u3000建立：{created}\u3000更新：{updated}',
 'save_memory': '保存记忆',
 'memory_title_required_title': '尚无标题',
 'memory_title_required': '请先填写记忆标题。',
 'memory_content_required_title': '尚无内容',
 'memory_content_required': '请先填写记忆内容。',
 'archived_memory_title': '已封存的长期记忆',
 'archived_memory_intro': '自动整理只会封存较旧、低重要度的对话记忆，不会直接销毁。您可以在这里随时勾选恢复。',
 'restore_checked_memories': '恢复勾选记忆',
 'close': '关闭',
 'archived_memory_item': '【{category}】{title}\n{content}\n封存原因：{reason}\u3000时间：{archived}',
 'archived_memory_count': '目前共有 {count} 则可恢复记忆',
 'archived_memory_select_title': '尚未选中',
 'archived_memory_select': '请先勾选要恢复的记忆。',
 'archived_memory_restored': '已恢复 {count} 则记忆。',
 'chat_history_title': '管理／清除对话',
 'chat_history_intro': '对话平时保存在本机，不会自动删除。请只勾选确定要永久删除的记录。',
 'delete_checked_chats': '删除勾选对话',
 'chat_history_item': '{created}｜{speaker}\n{content}',
 'chat_history_truncated_suffix': '（管理窗口最多显示最近 500 则）',
 'chat_history_status': '本机共保存 {count} 则对话。{suffix}',
 'chat_select_delete_title': '尚未勾选',
 'chat_select_delete': '请先勾选要删除的对话。',
 'chat_delete_title': '永久删除对话',
 'chat_delete_confirm': '确定永久删除勾选的 {count} 则对话吗？',
 'load_older_chat_tooltip': '每次向前加载 50 则本机对话',
 'manage_chat_tooltip': '勾选并删除指定对话，其他内容不受影响',
 'chat_zoom_out_tooltip': '缩小对话文字（Ctrl＋鼠标滚轮向下）',
 'chat_zoom_in_tooltip': '放大对话文字（Ctrl＋鼠标滚轮向上）',
 'chat_retention_status': '本机保存 {total} 则对话，目前显示最近 {shown} 则',
 'platform_name_required': '请先输入平台、系统或工具名称。',
 'platform_duplicate': '“{platform}”已存在，请使用不同名称。',
 'platform_added': '已添加工作平台：{platform}',
 'platform_delete_title': '删除工作平台',
 'platform_delete_confirm': '确定删除“{platform}”及其工作进度吗？此操作无法恢复。',
 'platform_not_found': '找不到工作平台：{platform}',
 'platform_deleted': '已删除工作平台：{platform}',
 'platform_url_missing_title': '尚未设置网址',
 'platform_url_missing': '请先在“{platform}”卡片填写网站或工具网址。',
 'platform_url_unsupported_title': '网址格式不支持',
 'platform_url_unsupported': '只允许打开 http:// 或 https:// 网址。',
 'permission_open_platform': '打开 {platform} 网站',
 'echo_guard_tooltip': '墨寒说话时暂停上传麦克风，播放结束后再恢复；启用时无法在她说话途中插话。',
 'hybrid_transcript_tooltip': 'Realtime 保留原生音频理解；每句说完后，界面文字改用完整录音的 OpenAI 高精度转录。成功后才允许墨寒回答。',
 'flagship_heading': '<b>旗舰控制中心</b>',
 'increase': '增加',
 'decrease': '减少',
 'voice_section': '语音',
 'profile_required_title': '尚缺必要资料',
 'profile_required': '助手名称与助手对您的称呼不可留空。',
 'send_chat_required_title': '尚未输入内容',
 'send_chat_required': '请先在左侧输入文字，再点击“发送”；也可以直接使用麦克风。',
 'thinking_status': '{assistant}思考中……',
 'answering_status': '回答中……',
 'api_connection_failed': 'OpenAI API：连接失败（{error}）',
 'voice_ready_short': '准备就绪',
 'voice_muted_short': '已静音',
 'sleep_mode_status': '休眠模式已启动；墨寒会保持安静，提醒与紧急警报仍会按规则处理。',
 'desktop_status_title': '墨寒正在桌面上与你互动',
 'desktop_status_description': '桌面上的墨寒是唯一可见、可拖动并会回应你的角色。',
 'desktop_status_mode': '模式',
 'desktop_status_expression': '姿态／表情',
 'desktop_status_voice': '语音',
 'desktop_status_vision': '镜头感知',
 'desktop_status_gesture': '手势',
 'desktop_status_idle': '待机中',
 'desktop_status_camera_waiting': '镜头待命',
 'desktop_status_gesture_waiting': '等待手势',
 'desktop_status_vision_present': '已看见你',
 'desktop_status_vision_away': '暂时未看见你',
 'desktop_status_vision_motion': '侦测到活动',
 'desktop_status_vision_unknown': '镜头待命',
 'desktop_status_gesture_wave': '已识别挥手',
 'microphone_idle': '🎙 麦克风',
 'microphone_send_now': '⏹ 立即发送',
 'microphone_recognizing': '识别中……',
 'voice_status_format': '语音状态：{phase}',
 'bubble_full_content': '……\n（完整内容请见对话页）',
 'tray_open_today': '打开今日待办',
 'tray_quit': '退出墨寒',
 'chat_retention': '对话保存在本机，不会自动删除',
 'load_older_chat': '加载更早对话',
 'manage_chat': '管理／清除对话',
 'chat_placeholder': '对墨寒说话……',
 'microphone': '🎙 麦克风',
 'send_text': '发送',
 'voice_ready': '语音状态：就绪',
 'speech_recognition': '单次麦克风识别',
 'transcription_model': '转录模型',
 'transcription_language': '转录语言',
 'transcription_prompt': '转录提示词／常用词',
 'windows_transcription_fallback': 'Windows 备用识别',
 'offline_fallback': '离线备用识别',
 'platform_offline_fallback_unavailable': '{platform} 离线识别尚未完成设备实测',
 'last_transcription': '最近转录诊断',
 'voice_engine': '朗读方式',
 'windows_voice': 'Windows 本机声音',
 'platform_local_voice': '{platform} 本机声音',
 'platform_local_voice_unavailable': '{platform} 本机语音尚未完成设备实测',
 'tts_voice': 'OpenAI 文字转语音声音',
 'realtime_output_source': 'Realtime 回复声音来源',
 'realtime_output_openai': 'OpenAI Realtime 原生语音（最低延迟，现有默认）',
 'realtime_output_azure': 'Azure Speech 女性声线（柔和流式播放）',
 'realtime_output_azure_hd': 'Azure Dragon HD 女性声线（需 S0）',
 'realtime_output_note_openai': '使用下方“OpenAI Realtime 原生声线”；延迟最低，完整保留 OpenAI Realtime 的原生实时语音输出。',
 'realtime_output_note_azure': '沿用上方“Azure Speech 女性声线”、区域与密钥。OpenAI Realtime 负责实时理解，Azure '
                               '以流式方式发声。',
 'realtime_output_note_azure_hd': '沿用上方“Dragon HD 女性声线”、S0 区域与独立密钥。OpenAI Realtime 负责实时理解，Dragon '
                                  'HD 以流式方式发声。',
 'realtime_voice': 'OpenAI Realtime 原生声线',
 'realtime_model': 'Realtime 模型',
 'realtime_transcription_model': 'Realtime 转录模型',
 'realtime_noise': 'Realtime 麦克风降噪',
 'realtime_turn': 'Realtime 轮次检测',
 'realtime_screen_transcript': 'Realtime 屏幕转录',
 'echo_guard': '回声防护',
 'local_rate': '本机语速',
 'mohan_volume': '墨寒音量',
 'voice_style': '语音风格',
 'realtime': 'Realtime 语音',
 'windows_engine': 'Windows 本机语音',
 'openai_engine': 'OpenAI 自然语音',
 'realtime_engine': 'Realtime 即时语音',
 'azure_engine': 'Azure Speech（预览）',
 'azure_hd_engine': 'Azure Dragon HD（预览，需 S0）',
 'azure_voice': 'Azure Speech 女性声线',
 'azure_region': 'Azure Speech 区域',
 'azure_key': 'Azure Speech 密钥',
 'azure_region_choose': '请选择创建 Azure 资源时所在的区域',
 'azure_region_saved': '现有设置 · {region}',
 'azure_key_saved': '已由 Windows 加密保存；留空即可保留',
 'azure_key_missing': '贴上 Azure Speech 资源密钥',
 'azure_remove_key': '移除 Azure Speech 密钥',
 'azure_remove_key_confirm': '确定移除由 Windows 加密保存的 Azure Speech 密钥吗？',
 'azure_key_save_failed': '无法安全保存 Azure Speech 密钥：{error}',
 'azure_hd_voice': 'Dragon HD 女性声线',
 'azure_hd_region': 'Dragon HD 资源区域',
 'azure_hd_key': 'Dragon HD S0 资源密钥',
 'azure_hd_key_saved': 'Dragon HD S0 密钥已由 Windows 加密保存；留空即可保留',
 'azure_hd_key_missing': '贴上独立的 Dragon HD S0 资源密钥',
 'azure_hd_remove_key': '移除 Dragon HD S0 密钥',
 'azure_hd_remove_key_confirm': '确定移除由 {platform} 安全保存的 Dragon HD S0 密钥吗？',
 'azure_hd_key_save_failed': '无法安全保存 Dragon HD S0 密钥：{error}',
 'azure_hd_speech_note': '可选预览功能；请使用独立的 S0 语音资源、密钥与相符区域。Dragon HD 不提供 '
                         'viseme，因此墨寒会沿用音频分析维持嘴型同步。发话前等待时间取决于网络与区域距离。若 HD 失败，会依序退回一般 Azure 与 '
                         'Windows 本机语音，每一层只尝试一次，避免重复计费。',
 'azure_speech_note': '预览功能；需自备 Azure Speech 资源密钥与相符区域。仅列出已确认的女性声线；设定不完整或服务失败时会立即切换到 Windows '
                      '女性语音。Azure 用量与费用以 Microsoft 官方规则为准。',
 'azure_speech_note_no_local_fallback': '预览功能；需自备 Azure Speech '
                                        '资源密钥与相符区域。此平台尚无已验证的本机语音，服务失败时会安全停止播放。',
 'azure_fallback_missing_settings': 'Azure Speech 尚未完成设定；已直接使用 Windows 女性语音，未发送云端请求。',
 'azure_missing_no_local_fallback': 'Azure Speech 尚未完成设置，且此平台没有已验证的本机语音；本次不会播放，也不会发送云端请求。',
 'no_female_voice': '未检测到已确认的女性 Windows 声音',
 'female_voice_note': '只显示 Windows 明确标示为女性的已安装声音，并优先选择与界面语言相符的声音。',
 'platform_local_voice_note': '{platform} 本机语音尚未完成设备实测；在完成前不会显示其他平台的声音，也不会宣称支持离线朗读。',
 'transcription_language_placeholder': 'ISO 语言代码；留空则自动检测',
 'openai_fallback': 'OpenAI 失败时使用 Windows 离线识别',
 'openai_recognition': 'OpenAI 高准确度识别（推荐）',
 'windows_recognition': 'Windows 离线识别',
 'no_transcription_error': '没有转录错误记录',
 'preview_voice': '试听：主上，妾在。',
 'realtime_disconnected': 'Realtime：未连接',
 'realtime_status_format': 'Realtime：{status}',
 'realtime_disconnected_status': '未连接',
 'realtime_error_status': '错误：{error}',
 'realtime_voice_title': 'Realtime 语音',
 'realtime_output_unavailable': 'Realtime Azure 语音输出服务尚未建立，未启动实时对话。',
 'start_realtime': '启动 Realtime 自然对话',
 'stop_realtime': '停止 Realtime 自然对话',
 'near_field': '近距离麦克风（推荐）',
 'far_field': '远距离／笔记本麦克风',
 'noise_off': '关闭降噪',
 'stable_vad': '稳定完整句（停顿约 0.85 秒）',
 'semantic_vad': '语义轮次（可能提前截断）',
 'echo_guard_option': '防止墨寒听见自己的声音',
 'hybrid_transcript': '屏幕使用高准确度最终转录',
 'mute': '静音',
 'rate_down': '降低本机语速',
 'rate_up': '提高本机语速',
 'level_suffix': ' 级',
 'realtime_note': 'Realtime 只在启用期间保持麦克风开启。稳定轮次会在您停止说话约 0.85 秒后送出；关闭 Realtime 会立即停止传送音频。',
 'model_access_note': '若 OpenAI 控制台已经启用模型却仍无法访问，请确认模型与 API Key 属于同一个 Project，再到设置页保存新密钥。',
 'echo_guard_note': '启用回声防护后，墨寒说话时会暂停上传麦克风音频，播放结束后再恢复。对话页只显示最终准确转录。',
 'recognition_note': '单次麦克风会在约 0.85 秒静音后送出音频，最长录制 10 秒；再次点击麦克风可提前送出。',
 'recognition_note_no_offline': '单次麦克风使用 OpenAI 高准确度识别；此平台的离线识别尚未完成设备实测，因此暂不显示离线备用识别。',
 'platform_secret_storage_unavailable': '{platform} 安全密钥保存尚未完成设备实测',
 'platform_autostart_unavailable': '{platform} 自动启动尚未完成设备实测',
 'autostart': '自动启动',
 'permissions_intro': '请分别授权每项能力。选择“每次询问”时，墨寒会在执行前请求确认；删除文件默认禁止。',
 'permission_open_web': '打开指定网站',
 'permission_open_folder': '打开工作文件夹',
 'permission_launch_app': '启动其他应用程序',
 'permission_write_files': '建立或修改文件',
 'permission_delete_files': '删除文件',
 'permission_deny': '禁止',
 'permission_ask': '每次询问',
 'permission_allow': '允许',
 'permissions_warning': '安全规则：对话内容不能扩大墨寒的权限。AI 可以提出工具请求，但实际能否执行只由本机权限设置决定。',
 'save_permissions': '保存工具权限',
 'permission_blocked': '权限已阻止',
 'permission_blocked_message': '墨寒目前无权{action}。',
 'permission_request': '墨寒请求电脑权限',
 'permission_request_message': '是否允许墨寒本次{action}？',
 'permission_saved_speech': '电脑权限已保存。妾会守住这些边界。',
 'profile_heading': '<b>身份与用户设置</b>',
 'system_heading': '<b>工作与系统设置</b>',
 'api_key': 'OpenAI API 密钥',
 'text_model': '文字模型',
 'persona_prompt': 'AI 人格提示词',
 'remove_api_key': '删除已保存的 API 密钥',
 'remove_api_key_confirm': '确定移除由 {platform} 安全保存的 OpenAI API 密钥吗？',
 'save_settings': '保存设置',
 'api_key_saved': '已安全保存；留空则保持不变',
 'api_key_missing': '粘贴以 sk- 开头的 OpenAI Project API Key',
 'api_key_save_failed': '无法安全保存 OpenAI API 密钥：{error}',
 'secret_auto_save_hint': '输入后按 Enter 或移开焦点，即会自动安全保存。',
 'api_status_saved': 'OpenAI API：密钥已由操作系统安全保存',
 'api_status_environment': 'OpenAI API：使用环境变量提供的密钥',
 'api_status_secret_unavailable': 'OpenAI API：{platform} 安全密钥保存尚未完成设备实测',
 'api_status_offline': 'OpenAI API：未设置，使用离线人格',
 'restart_language_note': '保存界面语言后，重新启动墨寒即可完整应用。',
 'about_heading': '<b>关于墨寒</b>',
 'about_body': (
     '墨寒桌面助手 v{version}，Copyright © 2026 CHOU MING HUA 与'
     ' MoHan Desktop Assistant 贡献者，依 MIT License 发行。<br>'
     '本软件以动态链接方式使用 Qt for Python（PySide6，GNU LGPL-3.0 授权）；'
     'Qt 库以独立文件封装于安装目录的 _internal 文件夹，您可自行检查或替换这些库。<br>'
     '完整第三方授权声明见安装目录的 THIRD_PARTY_NOTICES.md 与'
     ' third_party_licenses 文件夹；Qt 源代码可从'
     ' <a href="https://download.qt.io/official_releases/QtForPython/">'
     'Qt 官方下载存档</a>获取。'
 ),
 'reminder_work': '开始工作',
 'reminder_lunch': '午餐',
 'reminder_dinner': '晚餐',
 'reminder_offwork': '下班',
 'enabled': '启用',
 'reminder_message_label': '{label}消息',
 'reminder_message_placeholder': '此提醒触发时墨寒要说的内容',
 'continuous_work_reminder': '连续工作提醒',
 'overwork_message': '久坐／过劳提醒消息',
 'minutes_suffix': ' 分钟',
 'read_replies': '让墨寒读出回复',
 'voice_settings_saved': '语音设置已保存。',
 'settings_saved': '设置已保存。',
 'work_timer_already_running': '计时仍在进行，不必重复开始。',
 'work_timer_not_started': '今日尚未开始计时。'}
)

_JAPANESE: Mapping[str, str] = deep_freeze({
    **JAPANESE_UI,
    'tab_wardrobe': '雲裳閣',
     'cancel_without_saving': '保存せずに取り消す',
     'restore_dashboard_window': 'ウィンドウを元に戻す',
     'restore_dashboard_window_tooltip': 'コントロールセンターを移動・サイズ変更可能なウィンドウに戻します',
     'wardrobe_import': '衣装パッケージをインポート',
     'wardrobe_apply': '選択した衣装を適用',
     'wardrobe_restore_builtin': '内蔵衣装に戻す',
     'wardrobe_package_list': 'パッケージ一覧',
     'wardrobe_compatibility_status': '互換性状態',
     'wardrobe_status': '状態',
     'wardrobe_no_packages': '衣装パッケージはまだインストールされていません',
     'wardrobe_default_outfit': '内蔵の既定衣装',
     'wardrobe_compatible': '互換',
     'wardrobe_incompatible': '非互換',
     'wardrobe_status_ready': '雲裳システムの準備ができました',
     'wardrobe_validator_pending': 'パッケージは全視点の完全性と安全性の検証に合格していないため、インストールされませんでした。',
     'wardrobe_assets_pending': 'この衣装には全視点の完全な素材がないため、適用できません。',
     'wardrobe_builtin_applied': '内蔵の既定衣装を適用しました。',
     'wardrobe_outfit_applied': '選択した完全な衣装を適用しました。',
     'wardrobe_autonomous_enabled': '墨寒による自律的な衣装選択を許可',
     'wardrobe_self_generation_enabled': '墨寒によるクラウドでの新衣装生成を許可（料金が発生する場合があります）',
     'wardrobe_trend_search_enabled': '同意済みの5種類の状況情報で流行を検索し、独自デザインの着想に利用する（料金が発生する場合があります）',
     'wardrobe_generation_trend_search': '同意済みの5種類の状況情報で流行を検索し、新衣装を生成・監査・パッケージ化しています（料金が発生する場合があります）…',
     'wardrobe_image_quality': 'クラウド衣装生成の画質',
     'wardrobe_quality_low': '高速（低画質・最も時間と費用を節約）',
     'wardrobe_quality_medium': '標準（推奨）',
     'wardrobe_quality_high': '高精細（最も時間と費用がかかる）',
     'wardrobe_generated_limit': '自作衣装の保存上限',
     'wardrobe_storage_limit': '自作衣装の容量上限',
     'wardrobe_manual_lock_hours': '手動衣装のロック時間',
     'wardrobe_manual_lock_off': 'ロックしない',
     'wardrobe_generate_now': '新しい衣装を今すぐ生成（Image API を使用）',
     'wardrobe_generation_starting': '31視点の新衣装を作成し、安全監査を実行しています…',
     'wardrobe_generation_running': '新衣装を生成・監査・パッケージ化しています…',
     'wardrobe_generation_installed': '新衣装は監査に合格し、インストールして適用されました。',
     'wardrobe_generation_installed_manual_lock': '新衣装は監査に合格してインストールされました。手動で選んだ衣装はロック期限まで維持されます。',
     'wardrobe_generation_activation_failed': '新衣装は監査に合格してインストールされましたが、安全に適用できなかったため現在の衣装を維持します。',
     'wardrobe_generation_not_enabled': '先にクラウド衣装生成を有効にしてください。',
     'wardrobe_generation_no_key': '使用可能な OpenAI API キーが設定されていません。',
     'wardrobe_generation_capacity': '生成衣装の容量またはクールダウン上限に達しました。',
     'wardrobe_generation_cooldown': '自動生成は失敗後の待機中です。「新しい衣装を今すぐ生成」で手動再試行できます。',
     'wardrobe_generation_quarantined': '新衣装は監査に合格せず、適用せず隔離しました。',
     'wardrobe_generation_failed': '衣装生成に失敗し、素材はインストールされませんでした。',
     'wardrobe_generation_rate_limited': '画像サービスが混み合っています。墨寒は安全に再試行済みで、保存された進捗から後ほど再開できます。',
     'wardrobe_generation_auth_failed': 'OpenAI API キーの認証に失敗しました。設定タブでキーを保存し直してください。',
     'wardrobe_generation_access_denied': '現在の OpenAI プロジェクトには GPT Image 2 の利用権限がまだないか、組織認証が完了していません。',
     'wardrobe_generation_moderation_blocked': '今回の画像リクエストはプロバイダーの内容チェックを通過しなかったため、衣装庫には追加されませんでした。',
     'wardrobe_generation_invalid_request': '画像サービスが生成仕様を拒否しました。エラーは修復用に保存し、不完全な素材はインストールしていません。',
     'wardrobe_generation_network_unavailable': '現在、画像サービスに接続できません。不完全な素材はインストールしていません。',
     'wardrobe_generation_provider_unavailable': '画像サービスは一時的に利用できません。不完全な素材はインストールしていません。',
     'wardrobe_automatic_selection_disabled': '自律衣装選択は現在無効です。',
     'wardrobe_automatic_selection_failed': '自律選択に失敗したため、現在の衣装を維持しました。',
     'wardrobe_automatic_outfit_selected': '墨寒が状況に合わせて自律的に着替えました。',
     'wardrobe_pavilion_subtitle': '天候・気分・場面に合わせて墨寒が一式を選び、あなたの決定も尊重します。',
     'wardrobe_source_policy': '提供元を分離：炎剣公式・ユーザー導入・墨寒の自作',
     'dashboard_brand_line': '墨を骨とし・寒光を心とする',
     'wardrobe_character_preview': '墨寒スタイルプレビュー',
     'wardrobe_view_front': '正面',
     'wardrobe_view_left': '左側',
     'wardrobe_view_right': '右側',
     'wardrobe_view_back': '背面',
     'wardrobe_upload_single_file': 'ファイルを1つアップロード',
     'wardrobe_installed_inactive': 'インストール済み・未適用',
     'wardrobe_outfit_preview': '衣装プレビュー',
     'wardrobe_hairstyle_preview': '髪型プレビュー',
     'wardrobe_headwear_accessories': '髪飾り・アクセサリー',
     'wardrobe_preview_complete_look': '一式をまとめてプレビュー',
     'wardrobe_changes_after_save': '保存後に反映',
     'wardrobe_cancel_restores': '取り消して元に戻す',
     'wardrobe_remove_package': '追加パッケージを削除',
     'wardrobe_delete_confirm': '「{package}」を削除しますか？',
     'wardrobe_builtin_not_removable': '内蔵パッケージは削除できません',
     'wardrobe_switch_before_remove': '使用中のパッケージを切り替えてから削除してください',
     'wardrobe_missing_package_fallback': 'パッケージが見つからないため、現在の外観を維持しました',
     'theme_preview': 'テーマプレビュー',
     'theme_section_title': '<b>コントロールセンターのテーマ</b>',
     'theme_restore': 'テーマを元に戻す',
     'theme_source_official': '炎剣公式',
     'theme_source_user': 'ユーザー制作',
     'package_rejected_unsafe_or_missing': '危険な内容または不足ファイルがあるため、パッケージ全体を拒否しました',
     'appearance_category_outfit': '衣装',
     'appearance_category_hairstyle': '髪型',
     'appearance_category_headwear': '髪飾り',
     'appearance_category_accessory': 'アクセサリー',
     'appearance_no_headwear': '髪飾りなし'
})

MODE_LABELS: Mapping[str, str] = frozendict(
{'工作': 'Work',
 '陪伴': 'Companion',
 '勿擾': 'Do not disturb',
 '會議': 'Meeting',
 '離席': 'Away',
 '休眠': 'Sleep'}
)

WORK_TYPE_LABELS: Mapping[str, str] = frozendict(
{'一般辦公／行政': 'General office / administration',
 '專案管理': 'Project management',
 '自由工作者／接案': 'Freelance / contract work',
 '創作／內容工作': 'Creative / content work',
 '軟體開發／技術': 'Software development / technology',
 '教育／研究': 'Education / research',
 '銷售／客戶服務': 'Sales / customer service',
 '其他（可自行輸入）': 'Other (enter your own)'}
)

PLATFORM_STATUS_LABELS: Mapping[str, str] = frozendict(
{'尚未開始': 'Not started',
 '準備資料': 'Preparing materials',
 '進行中': 'In progress',
 '待送出': 'Ready to submit',
 '等待回覆': 'Waiting for response',
 '審核中': 'Under review',
 '需修正': 'Needs revision',
 '已排程': 'Scheduled',
 '已完成': 'Completed',
 '已上架': 'Published',
 '暫停': 'Paused'}
)

MEMORY_CATEGORY_LABELS: Mapping[str, str] = frozendict(
{'人物': 'People',
 '偏好': 'Preferences',
 '目標': 'Goals',
 '工作流程': 'Workflows',
 '重要日期': 'Important dates',
 '其他': 'Other'}
)

SIMPLIFIED_MODE_LABELS: Mapping[str, str] = frozendict(
{'工作': '工作', '陪伴': '陪伴', '勿擾': '勿扰', '會議': '会议', '離席': '离席', '休眠': '休眠'}
)

SIMPLIFIED_WORK_TYPE_LABELS: Mapping[str, str] = frozendict(
{'一般辦公／行政': '一般办公／行政',
 '專案管理': '项目管理',
 '自由工作者／接案': '自由职业／承接项目',
 '創作／內容工作': '创作／内容工作',
 '軟體開發／技術': '软件开发／技术',
 '教育／研究': '教育／研究',
 '銷售／客戶服務': '销售／客户服务',
 '其他（可自行輸入）': '其他（可自行输入）'}
)

SIMPLIFIED_PLATFORM_STATUS_LABELS: Mapping[str, str] = frozendict(
{'尚未開始': '尚未开始',
 '準備資料': '准备资料',
 '進行中': '进行中',
 '待送出': '待提交',
 '等待回覆': '等待回复',
 '審核中': '审核中',
 '需修正': '需修改',
 '已排程': '已排期',
 '已完成': '已完成',
 '已上架': '已发布',
 '暫停': '暂停'}
)

SIMPLIFIED_MEMORY_CATEGORY_LABELS: Mapping[str, str] = frozendict(
{'人物': '人物', '偏好': '偏好', '目標': '目标', '工作流程': '工作流程', '重要日期': '重要日期', '其他': '其他'}
)

def ui_text(language: str, key: str, chinese: str, **values: object) -> str:
    if is_english(language):
        text = _ENGLISH.get(key, chinese)
    elif is_simplified_chinese(language):
        text = _SIMPLIFIED_CHINESE.get(key, chinese)
    elif is_japanese(language):
        text = _JAPANESE.get(key, chinese)
    else:
        text = chinese
    return text.format(**values) if values else text


def display_label(
    language: str,
    value: str,
    english: Mapping[str, str],
    simplified: Mapping[str, str] | None = None,
    japanese: Mapping[str, str] | None = None,
) -> str:
    if is_english(language):
        return english.get(value, value)
    if is_simplified_chinese(language) and simplified is not None:
        return simplified.get(value, value)
    if is_japanese(language) and japanese is not None:
        return japanese.get(value, value)
    return value


__all__ = (
    "MEMORY_CATEGORY_LABELS",
    "MODE_LABELS",
    "PLATFORM_STATUS_LABELS",
    "SIMPLIFIED_MEMORY_CATEGORY_LABELS",
    "SIMPLIFIED_MODE_LABELS",
    "SIMPLIFIED_PLATFORM_STATUS_LABELS",
    "SIMPLIFIED_WORK_TYPE_LABELS",
    "WORK_TYPE_LABELS",
    "_ENGLISH",
    "_JAPANESE",
    "_SIMPLIFIED_CHINESE",
    "display_label",
    "ui_text",
)
