"""Compatibility re-exports for canonical character-pack data contracts."""

from __future__ import annotations

lazy from domain.character_pack.character_data_models import (
    DEFAULT_EXPRESSION_CATALOG_PATH,
    DEFAULT_RIG_MANIFEST_PATH,
    EXPRESSION_SCHEMA,
    FULL_BODY_LAYER_COUNT,
    FULL_VIEW_COUNT,
    HAND_LANDMARK_COUNT,
    MAX_CHANNEL_VALUE,
    MAX_PITCH_DEGREES,
    MAX_YAW_DEGREES,
    MIN_PITCH_DEGREES,
    PAIR_LENGTH,
    RECT_LENGTH,
    RIG_SCHEMA,
    SCHEMA_VERSION,
    TRIPLE_LENGTH,
    ArmSpec,
    BodyMeasurementsSpec,
    BodyProportionsSpec,
    BrowGuardSpec,
    CanvasSpec,
    CharacterDataError,
    CharacterRigManifest,
    ExpressionRuleSpec,
    ExpressionStateCatalog,
    FaceCalibrationSpec,
    FacePoseAssetSpec,
    FullBodyCalibrationSpec,
    PhysicsSpec,
    PoseSpec,
    SourceBoundExasperatedSpec,
    ViewportSpec,
    ViewRingSpec,
)

__all__ = (
    "DEFAULT_EXPRESSION_CATALOG_PATH",
    "DEFAULT_RIG_MANIFEST_PATH",
    "EXPRESSION_SCHEMA",
    "FULL_BODY_LAYER_COUNT",
    "FULL_VIEW_COUNT",
    "HAND_LANDMARK_COUNT",
    "MAX_CHANNEL_VALUE",
    "MAX_PITCH_DEGREES",
    "MAX_YAW_DEGREES",
    "MIN_PITCH_DEGREES",
    "PAIR_LENGTH",
    "RECT_LENGTH",
    "RIG_SCHEMA",
    "SCHEMA_VERSION",
    "TRIPLE_LENGTH",
    "ArmSpec",
    "BodyMeasurementsSpec",
    "BodyProportionsSpec",
    "BrowGuardSpec",
    "CanvasSpec",
    "CharacterDataError",
    "CharacterRigManifest",
    "ExpressionRuleSpec",
    "ExpressionStateCatalog",
    "FaceCalibrationSpec",
    "FacePoseAssetSpec",
    "FullBodyCalibrationSpec",
    "PhysicsSpec",
    "PoseSpec",
    "SourceBoundExasperatedSpec",
    "ViewRingSpec",
    "ViewportSpec",
)
